<a href="https://colab.research.google.com/github/tekliyetamiru/Natural-Language-Processing-NLP-with-TensorFlow/blob/main/Natural_Language_Processing_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction of NLP Fundamentals in TensorFlow
NLP has the goal of deriving information out of natural language (could be sequences text or speech).

Another common term for NLP problem is sequence to sequence problems(seq2seq)

# Check for GPU

In [ ]:
!nvidia-smi -L

## Get helper functions

In [ ]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/refs/heads/main/extras/helper_functions.py

# Import series of helper functions for the notebook
from helper_functions import unzip_data,create_tensorboard_callback,plot_loss_curves, compare_historys

--2025-11-04 08:10:47--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/refs/heads/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2025-11-04 08:10:47 (62.1 MB/s) - ‘helper_functions.py’ saved [10246/10246]



## Get a text Dataset

The dataset we're going to be using is kaggle's introduction to NLP dataset ( text samples of Tweets labelled as disaster or not disaster).

See the orginal here: https://www.kaggle.com/c/nlp-getting-started

In [ ]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

--2025-11-04 08:11:07--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 74.125.128.207, 74.125.143.207, 173.194.69.207, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|74.125.128.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  1.28MB/s    in 0.5s    

2025-11-04 08:11:08 (1.28 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



In [ ]:
unzip_data("nlp_getting_started.zip")

## Visualizing a text dataset

To visualize out text samples,we first have to read them in, one way to do so would be to use python: https://realpython.com/read-write-files-python/

But I prefer to get visual straight way.
So another way to do this is to use pandas...

In [ ]:
import pandas as pd
train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")
train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [ ]:
train_df["text"][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

In [ ]:
# shuffle training dataframe
train_df_shuffled=train_df.sample(frac=1,random_state=42)
train_df_shuffled.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [ ]:
# what does the test dataframe look like?
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [ ]:
# how many examples of each class?
train_df.target.value_counts()

target
0    4342
1    3271
Name: count, dtype: int64

In [ ]:
# how many total samples?
len(train_df), len(test_df)

(7613, 3263)

In [ ]:
# Let's visualize some random training examples
import random
random_index=random.randint(0,len(train_df)-5) # create random indexes not higher than the total number of samples
for row in train_df_shuffled[["text","target"]][random_index:random_index+5].itertuples():
  _,text,target=row
  print(f"Target:{target}","(real diaster)" if target>0 else "(not real diaster)")
  print(f"Text:\n{text}\n")
  print("---\n")

Target:0 (not real diaster)
Text:
#Camera #Art #Photography http://t.co/TJGxDc3D5p #0215 New BoltåÊCyclone DR PP-400DR Dual Outlet Power PackåÊFor External Camera Flash

$30‰Û_

---

Target:0 (not real diaster)
Text:
Doing dialyses to my grandpa and oh lord this blood makes me light headed

---

Target:1 (real diaster)
Text:
./.....hmm 12000 Nigerian refugees repatriated from Cameroon http://t.co/96p3hUJNTj /(

---

Target:0 (not real diaster)
Text:
To ouvindo sleeping with sirens awn

---

Target:1 (real diaster)
Text:
#ModiMinistry Madhya Pradesh Train Derailment: Village Youth Saved Many Lives http://t.co/YvMpHd0z9X

---



### Split data into training and validation sets

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# Use train_test_split to split training data into training and validation sets
train_sentences,val_sentences,train_labels, val_labels = train_test_split(train_df_shuffled["text"].to_numpy(),
                                                                          train_df_shuffled["target"].to_numpy(),
                                                                          test_size=0.1, #use 10% of training data for valid
                                                                          random_state=42)


In [ ]:
# Check the lengths
len(train_sentences), len(val_sentences),len(train_labels),len(val_labels)

(6851, 762, 6851, 762)

In [ ]:
# Check the first 10 samples
train_sentences[:10],train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object),
 array([0,

## Converting text into numbers

When dealing with a text problem, one of the first things you'll to do before you can build a model is to convert your text to numbers.

There are a few ways to do this, namely:
* Tokenziation - direct mapping of token (a token could be a word or a character) to number
* Embedding - create a matrix of teature vector for each token(this size of the features vector can be defined and this embedding can be learned)


### Text Vectorization(tokenization)

In [ ]:
train_sentences[:5]

array(['@mogacola @zamtriossu i screamed after hitting tweet',
       'Imagine getting flattened by Kurt Zouma',
       '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
       "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
       'Somehow find you and I collide http://t.co/Ee8RpOahPk'],
      dtype=object)

In [ ]:
from os.path import split
import tensorflow as tf
from tensorflow.keras.layers import TextVectorization


# Use the default TextVectorization parameters

text_vectorizer = TextVectorization(max_tokens=None, # how many words in the vocabulary (automatically add <OOV>)
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None, # Create groups of n-words?
                                    output_mode="int", # how to map token to numbers
                                    output_sequence_length=None, # how long do you want your sequences to be?
                                    pad_to_max_tokens=True)



In [ ]:
train_sentences[0].split()

['@mogacola', '@zamtriossu', 'i', 'screamed', 'after', 'hitting', 'tweet']

In [ ]:
# Find the average number of token (words) in the training tweets
round(sum([len(i.split()) for i in train_sentences])/len(train_sentences))

15

In [ ]:
for i in train_sentences[:5]:
  print(i.split(),"\n")


['@mogacola', '@zamtriossu', 'i', 'screamed', 'after', 'hitting', 'tweet'] 

['Imagine', 'getting', 'flattened', 'by', 'Kurt', 'Zouma'] 

['@Gurmeetramrahim', '#MSGDoing111WelfareWorks', 'Green', 'S', 'welfare', 'force', 'ke', 'appx', '65000', 'members', 'har', 'time', 'disaster', 'victim', 'ki', 'help', 'ke', 'liye', 'tyar', 'hai....'] 

['@shakjn', '@C7', '@Magnums', 'im', 'shaking', 'in', 'fear', "he's", 'gonna', 'hack', 'the', 'planet'] 

['Somehow', 'find', 'you', 'and', 'I', 'collide', 'http://t.co/Ee8RpOahPk'] 



In [ ]:
# Setup text vectorization variables
max_vocab_length = 10000 # max number of words to have in our vacabulary
max_length = 15 # max length our sequences will be (e.g. how many words from a tweet does a model see?)

text_vectorizer=TextVectorization(
    max_tokens=max_vocab_length,
    output_mode="int",
    output_sequence_length=max_length
)



In [ ]:
# Fit the text vectorizer to the training text
text_vectorizer.adapt(train_sentences)

In [ ]:
# Create a sample sentence and tokenize it
sample_sentence= "There's a flood in my street!"
text_vectorizer([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   1,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [ ]:
# Choose a random sentence from the training dataset and tokenize it
random_sentence=random.choice(train_sentences)
print(f"Original text:\n {random_sentence} \\n\nVectorized Version:")
text_vectorizer([random_sentence])

Original text:
 Messi: has tattoos so he can't donate blood
Ronaldo: runs into burning buildings to save dogs #respect \n
Vectorized Version:


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[5136,   41, 7785,   28,   56,   98, 3917,  353, 4720, 1484,   66,
          86,   95,    5,  328]])>

In [ ]:
# Get the unique words in the vocabulary
words_in_vocab=text_vectorizer.get_vocabulary() # get all of the unique words in our training data
top_5_words = words_in_vocab[:5] # get the most common words
bottom_5_words = words_in_vocab[-5:] # get the least common words

print(f"Number of words in vocab:{len(words_in_vocab)}")
print(f"5 most common words:{top_5_words}")
print(f"5 least common words:{bottom_5_words}")

Number of words in vocab:10000
5 most common words:['', '[UNK]', np.str_('the'), np.str_('a'), np.str_('in')]
5 least common words:[np.str_('pages'), np.str_('paeds'), np.str_('pads'), np.str_('padres'), np.str_('paddytomlinson1')]


## Creating an Embedding using an Embedding Layer

To make out embedding, we're going to use TensorFlow's embedding layer: https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding


The parameters we care most about for our embedding layer:
* `input_dim` = the size of our vocabulary
* `output_dim` = the size of the output embedding vector, for example, a value of 100 would mean each token gets represented by a vector 100 long
* `input_length` = length of the sequences being passed to the embedding layer


In [ ]:
from tensorflow.keras import layers
embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128, # output shape
                             input_length=max_length # how long is each input
                             )
embedding

<Embedding name=embedding_1, built=False>

In [ ]:
# Get a random sentence from the training set
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\
      \n\nEmbedded version:")

# Embed the random sentence (turn it into dense vectors of fixed size)
sample_embed = embedding(text_vectorizer([random_sentence]))
sample_embed

Original text:
 Learn How I Gained Access To The Secrets Of The Top Earners &amp; Used Them To Explode My Home Business Here: http://t.co/e84IFMCczN Please #RT      

Embedded version:


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[-0.02531172, -0.02525865,  0.00536426, ..., -0.03173308,
         -0.03987824, -0.01374609],
        [ 0.04785806, -0.029708  ,  0.00674739, ...,  0.01423131,
         -0.0184695 ,  0.04943177],
        [ 0.00255124, -0.00812116, -0.02874906, ...,  0.01663088,
          0.00978377,  0.04592568],
        ...,
        [ 0.02972618,  0.04327017,  0.02027676, ...,  0.02492766,
         -0.02372594, -0.02519247],
        [ 0.03784237,  0.01864389, -0.02399877, ...,  0.01510991,
         -0.03922653, -0.02224205],
        [-0.02173843,  0.01573804, -0.00310395, ..., -0.02385162,
          0.03038224,  0.01732074]]], dtype=float32)>

In [ ]:
# check out a single token's embedding
sample_embed[0][0], sample_embed[0][0].shape, random_sentence[0]


(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([-0.02531172, -0.02525865,  0.00536426,  0.04706872,  0.01711266,
         0.03688803,  0.02721036,  0.03021869, -0.00944873,  0.0465898 ,
        -0.02787547,  0.01594844,  0.0125686 ,  0.00660314, -0.03622771,
         0.00089711,  0.03141946,  0.00365814,  0.04938667,  0.02433432,
        -0.0382819 , -0.001107  ,  0.01401604,  0.01976905,  0.03216025,
        -0.0385061 , -0.01945237,  0.04991465, -0.02813645,  0.04322103,
         0.03999704,  0.01976432,  0.04191506, -0.00694935,  0.02863609,
         0.04480517,  0.02033171,  0.0026342 ,  0.03104378,  0.04412848,
        -0.02423712, -0.00238059,  0.0345795 , -0.01623899, -0.03691473,
        -0.0173304 , -0.00363662, -0.0370348 , -0.018136  , -0.04132351,
         0.03045212,  0.04845972, -0.00829172, -0.01581477,  0.03194353,
        -0.04621202, -0.03302525,  0.03401392,  0.00446843,  0.00800122,
         0.00678091, -0.03693886,  0.01284338, -0.02306124,  0.00576542,
  